_BASE_: "Two-Base-CTW1500.yaml"
DATASETS:
  TRAIN: ("ctw1500_word_train_with_ignore",)
  TEST: ("ctw1500_word_just_test",)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "TextCrowdedBestInnerAttentionFCROIHeads"
    SCORE_THRESH_TEST: 0.7
    NMS_THRESH_TEST: 0.35
  ROI_BOX_HEAD:
    NUM_CONV: 2
    NUM_FC: 2
SOLVER:
  WARMUP_ITERS: 500
  IMS_PER_BATCH: 1
  BASE_LR: 0.0025
  STEPS: (32000,100000)
  MAX_ITER: 150000
  # MAX_ITER: 20000
  CHECKPOINT_PERIOD: 4000
INPUT:
  CROP:
    ENABLED: True
  ROTATE:
    ENABLED: False
    ANGLE_TRAIN: (-20,20)
    ANGLE_TRAIN_SAMPLING: 'range'
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "output/ablation/ctw_w_ignore/crowd_inner_attention_fc_0304"

