_BASE_: "Two-Base-Stamp.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NAME: "StandardROIHeads"
    SCORE_THRESH_TEST: 0.8
    NMS_THRESH_TEST: 0.3
  ROI_BOX_HEAD:
    NUM_CONV: 2
    NUM_FC: 2
SOLVER:
  WARMUP_ITERS: 500
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  # IMS_PER_BATCH: 16
  # BASE_LR: 0.02
  STEPS: (6000,8000)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 1000
DATASETS:
  TRAIN: ("synth_stamp_train_0803", )
  TEST: ("stamp_train",)
INPUT:
  CROP:
    ENABLED: True
  ROTATE:
    ENABLED: False
    ROTATE_TRAIN_PRO: 1.0
    ANGLE_TRAIN: (-20,20)
    ANGLE_TRAIN_SAMPLING: 'range'
TEST:
  EVAL_PERIOD: 1000
  AUG:
    ENABLED: False
    FLIP: False
    MAX_SIZE: 1600
    MIN_SIZES: (1200,)
OUTPUT_DIR: "output/batext/stamp/two_attn_R_50_synth_only_0803"
